apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
  labels:
    {{- include "chefbook-certificates.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ include "chefbook-certificates.server" . }}
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
